---
# tasks file for network
  - name: Add a new tenant
    cisco.aci.aci_tenant:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: test
      description: test_tenant
      state: present
    delegate_to: localhost
